version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: dara-portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - portfolio-network
    # Uncomment the following lines if you need to set environment variables
    # env_file:
    #   - .env.local
    
  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: portfolio-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - portfolio
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# Optional: Add volumes for persistent data
# volumes:
#   portfolio-data: 